### ISSUE TITLE
RadMaskedInput IpAddress sample: broken paste functionality

### ISSUE THREAD

**Issue by stilettk** [telerik/xaml-sdk#10]
`RadMaskedInput`, IpAddress sample.
If you paste "1.1.1.1" in the address field, it will result in "111.1.." instead of "001.001.001.001"

**Comment by DinkoK** [comment]
the RadMaskedInput controls don't support IP address validation out of the box. You can find a runnable solution that demonstrates RadMaskedInput control that accepts an IP address in our [GitHub repository](https://github.com/telerik/xaml-sdk/tree/master/MaskedInput/IpAddress). In your case, you can manually validate the copied IpAddress before pasting it into the mask.

**Comment by stilettk** [comment]
I understand this. But I think that example must be fully functional so that people could use it.

**Comment by DinkoK** [comment]
Hi stilettk,

Thank you for your feedback. Indeed there could be cases in which the provided example could not cover. But we think this SDK example is a good starting for achieving your final behavior. 

I am happy to inform you that with the latest version of our controls we have added [Regex Validation](https://docs.telerik.com/devtools/wpf/controls/radmaskedinput/features/validation/regex-validation) to the RadMaskedTextInput control. The regex validation feature provides out of the box validation for Email and IP address.
