### ISSUE TITLE
RadRichTextBox - Apostrophe separates word while spell checking

### ISSUE THREAD

**Issue by atabeata** [telerik/xaml-sdk#12]
While checking the word with an apostrophe like "I've", the "CheckWordIsCorrect" method is checking only "ve" (instead of "I've"). The apostrophe is treated as a words separator and because of that the "I've" word is marked as incorrect.

How can I check words with apostrophes? 

Thanks,
Beata

**Comment by bsivanov** [comment]
If I am not wrong, we've discussed this problem in a support ticket and it's related to known issue in RadRichTextBox: [RichTextBox: Words with apostrophes are considered invalid by the spell checker](https://feedback.telerik.com/Project/143/Feedback/Details/193941-richtextbox-words-with-apostrophes-are-considered-invalid-by-the-spell-checker). I am closing the issue, as it's not related to the examples itself.
