### ISSUE TITLE
Too slow when selecting more than 5K rows

### ISSUE THREAD

**Issue by maciz84** [telerik/xaml-sdk#13]
Hi Guys,

How can I make selecting and transfering to target faster as it is very slow when more than 5K rows?

**Comment by bsivanov** [comment]
Could you specify which example you are referring to?

**Comment by maciz84** [comment]
Hi there,

I am referring to the BindingSelectedItemsFromViewModel example From A few years back. The transfer part of the code is too slow. I wouldn't complain if it was an asymc method where I could at least show a loading panel or something

**Comment by maciz84** [comment]
Has this been updated?

**Comment by maciz84** [comment]
[http://www.telerik.com/blogs/how-to-synchronize-your-ui-selected-items-with-your-data-context-using-mvvm-and-blend-behaviors-for-silverlight-and-wpf](url)

**Comment by maciz84** [comment]
The code i user is below:

`using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using Telerik.Windows.Controls;
using System.Collections.Specialized;

public class MySelectedItemsBindingBehavior : ViewModelBase
{
	private readonly RadGridView grid = null;
	private readonly INotifyCollectionChanged selectedItems = null;
	private Boolean isSubscribedToEvents = false;

	private static Boolean isAttached = false;


	public static readonly DependencyProperty SelectedItemsProperty = DependencyProperty.RegisterAttached("SelectedItems", typeof(INotifyCollectionChanged), typeof(MySelectedItemsBindingBehavior), new PropertyMetadata(new PropertyChangedCallback(OnSelectedItemsPropertyChanged)));
	public static void SetSelectedItems(DependencyObject dependencyObject, INotifyCollectionChanged selectedItems)
	{
		dependencyObject.SetValue(SelectedItemsProperty, selectedItems);
	}

	public static INotifyCollectionChanged GetSelectedItems(DependencyObject dependencyObject)
	{
		return (INotifyCollectionChanged)dependencyObject.GetValue(SelectedItemsProperty);
	}

	private static void OnSelectedItemsPropertyChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e)
	{
		RadGridView grid = dependencyObject as RadGridView;
		INotifyCollectionChanged selectedItems = e.NewValue as INotifyCollectionChanged;

		if (grid != null && selectedItems != null) {
			MySelectedItemsBindingBehavior behavior = new MySelectedItemsBindingBehavior(grid, selectedItems);
			behavior.Attach();
			isAttached = true;
		}

		//If grid IsNot Nothing AndAlso selectedItems IsNot Nothing AndAlso Not isAttached Then
		//    Dim behavior As New MySelectedItemsBindingBehavior(grid, selectedItems)
		//    behavior.Attach()
		//    isAttached = True
		//End If
	}

	private void Attach()
	{
		if (grid != null && selectedItems != null) {
			Transfer(GetSelectedItems(grid) as IList, grid.SelectedItems);
			SubscribeToEvents();
		}
	}

	public MySelectedItemsBindingBehavior(RadGridView grid, INotifyCollectionChanged selectedItems)
	{
		this.grid = grid;
		this.selectedItems = selectedItems;
	}

	private void ContextSelectedItems_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
	{
		UnsubscribeFromEvents();

		Transfer(GetSelectedItems(grid) as IList, grid.SelectedItems);


		SubscribeToEvents();
	}

	private void GridSelectedItems_CollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
	{
		UnsubscribeFromEvents();

		Transfer(grid.SelectedItems, GetSelectedItems(grid) as IList);

		SubscribeToEvents();
	}

	private void SubscribeToEvents()
	{
		if (!isSubscribedToEvents) {
			grid.SelectedItems.CollectionChanged += GridSelectedItems_CollectionChanged;

			if (GetSelectedItems(grid) != null) {
				GetSelectedItems(grid).CollectionChanged += ContextSelectedItems_CollectionChanged;
			}
			isSubscribedToEvents = true;
		}
	}

	private void UnsubscribeFromEvents()
	{
		if (isSubscribedToEvents) {
			grid.SelectedItems.CollectionChanged -= GridSelectedItems_CollectionChanged;

			if (GetSelectedItems(grid) != null) {
				GetSelectedItems(grid).CollectionChanged -= ContextSelectedItems_CollectionChanged;
			}
			isSubscribedToEvents = false;
		}
	}

	public static void Transfer(IList source, IList target)
	{
		if (source == null || target == null) {
			return;
		}

		target.Clear();

		foreach (object o in source) {
			target.Add(o);
		}

	}
}`

**Comment by martinivanoff** [comment]
Hello,

Thank you for reporting this. We just fixed it and the update will be live within the next week. In the meantime you can use the [GridUtilities ](https://github.com/telerik/xaml-sdk/blob/master/ChartView/WPF/BindingSelectedItemsToViewModel/ChartUtilities.cs) class from the ChartView BindingSelectedItemsToViewModel example.

Regards,
Martin Ivanov
Technical Support Engineer
