### ISSUE TITLE
routing not working

### ISSUE THREAD

**Issue by nuelle1605** [telerik/xaml-sdk#19]
server always returns: error 400 bad request

even though API key is valid

**Comment by martinivanoff** [comment]
Hello, 

Can you please tell me which SDK example you are using? Is it the [Routing](https://github.com/telerik/xaml-sdk/tree/master/Map/WPF/Routing) of RadMap? Also, can you list the steps to reproduce the issue?

Thank you,
Martin Ivanov
Technical Support Engineer

**Comment by nuelle1605** [comment]
Hello Martin

basically I just followed the example at:
[https://docs.telerik.com/devtools/wpf/controls/radmap/features/providers/bing-rest-map-provider/routing](url)

`var aRequest = new BingRestRouteRequest();
aRequest.Culture = new System.Globalization.CultureInfo("sv-SE");

LocationCollection wayPoints = new LocationCollection();
foreach (var aStop in qStops)
{
	if (aStop.MapLocation.HasValue)
		wayPoints.Add(aStop.MapLocation.Value);                    
}
				
foreach (var point in wayPoints)
{
    aRequest.Waypoints.Add(point.ToString());
}
				
aRequest.Options.RouteAttributes = BingRestRouteAttributes.RoutePath;
aRequest.DistanceUnit = DistanceUnit.Kilometer;

this._RouteProvider.CalculateRouteAsync(aRequest);`


error 400 bad request 

Best regards
Alexander

**Comment by nuelle1605** [comment]
Hi Martin

my comment is updated, but I unfortunately closed the issue.
Could you reopen it?

Thanks in advance.

Alexander
