### ISSUE TITLE
The data context needs to get reassigned here

### ISSUE THREAD

**Issue by plucked** [telerik/xaml-sdk#29]
https://github.com/telerik/xaml-sdk/blob/7319f50c21f5416429ff5751e9b5c2fb4aaba9a5/Docking/VisualStudioDocking/CustomSaveLoadLayoutHelper.cs#L11

Reproduce:

1. Open the app
2. Open some documents
3. Close the app
4. Open the app again
5. Close some documents

You will see that the connection between the RadPane and the view model got lost, because the data context needs to get reassigned. 

The fix in my code looks like this (using .net Core 3 with C# 8)
```
protected override void ElementLoadedOverride(string serializationTag, DependencyObject element) {
            base.ElementLoadedOverride(serializationTag, element);
            var model = DataSource.Panes.FirstOrDefault(viewModel => viewModel.SerializationTag == serializationTag);
            if (model == null) {
                return;
            }

            /// ... Control instancing code

            // reassign the data context, otherwise we have no connection when it gets closed
            if (element is FrameworkElement frameworkElement) {
                frameworkElement.DataContext = model;
            }
        }
```

**Comment by martinivanoff** [comment]
Hello,

Can you tell me what do you mean by saying that the connection between the RadPane and the view model is lost? How do you indicate this?

Thank you for any help you can provide.

Regards,
Martin Ivanov
Telerik WPF Team
