### ISSUE TITLE
ObjectStateManager Exception in SQLExceptionAppointment.cs

### ISSUE THREAD

**Issue by Ivandrago1988** [telerik/xaml-sdk#30]
Hello guys,
Im new in C#. I start to reproduce this solution to my Database and so on.
All worked great, but when i start the Project the second time it throw this Exception:

![image](https://user-images.githubusercontent.com/56172767/67949237-ab367200-fbe7-11e9-8289-dcca7b8736dc.png)

In English:  

System.InvalidOperationException: 'An object with the same key already exists in the ObjectStateManager. The existing object is in the 'Unchanged' state. An object can only be added to the ObjectStateManager again when it is in the added state. '

The ObjectStateManger is handled in the SQLExceptionAppointment.cs.

Any Solution?
Thx for Help

**Comment by martinivanoff** [comment]
Hello Ivan

I've tested this on my side, but couldn't reproduce the error. Can you tell me what modification should be made in the original example in order to reproduce this?

Regards,
Martin Ivanov
Telerik WPF Team
