### ISSUE TITLE
Binding Error in Telerik Editor User control 

### ISSUE THREAD

**Issue by abdou31** [telerik/xaml-sdk#34]
Good morning, 

I have used the Telerik Editor User Control ( RadRichTextbox ribbon UI ) and I call it in my window, it works fine, but it was very slow in the starts of the window opening that contains the Telerik Editor UC, when I see in the output command line, I observe two errors of binding :

> System.Windows.Data Error: 40 : BindingExpression path error: 'StyleDefinitions' property not found on 'object' ''RichTextBoxCommands' (HashCode=22325706)'. BindingExpression:Path=StyleDefinitions; DataItem='RichTextBoxCommands' (HashCode=22325706); target element is 'RadRibbonGallery' (Name='radRibbonGallery'); target property is 'ItemsSource' (type 'IEnumerable')
>System.Windows.Data Error: 40 : BindingExpression path error: 'CurrentSelectedStyle' property not found on 'object' ''RichTextBoxCommands' (HashCode=22325706)'. BindingExpression:Path=CurrentSelectedStyle; DataItem='RichTextBoxCommands' (HashCode=22325706); target element is 'RadRibbonGallery' (Name='radRibbonGallery'); target property is 'SelectedValue' (type 'Object') 

Are these errors are related to the slow of the window?
If yes , how can I fix them?

**Comment by TanyaDimitrova** [comment]
Hi @abdou31,
The initial loading time of the control is affected by the leading of all the extensible components that is done using MEF. You can disable the loading with the MEF by setting the type catalog of the control. You can find an example of how to do that in the [Initial Load Performance of RadRichTextBox](https://docs.telerik.com/devtools/wpf/controls/radrichtextbox/mef#initial-load-performance-of-radrichtextbox) help section.
