### ISSUE TITLE
sheduleview code first for entity framework core

### ISSUE THREAD

**Issue by drkhodakarami** [telerik/xaml-sdk#46]
Hi
In the ScheduleViewEntities class where you are defining the mapping, it works with .net frame work how ever, entity frame work core, has no .WithRequired and no .WithOptional methods on defining relations, can you please give us a working class for entity frame work core?
thanks

**Comment by vladimir-stoyanov** [comment]
Currently we do not have an SDK example that demonstrates the usage of RadScheduleView with a database in .NetCore or a later version. You can log a new feature request in our [feedback portal](https://feedback.telerik.com/wpf), if that is something that will be beneficial for you.

For the time being, you can check out the following forum posts: [WithRequired() No Extension Method Defined](https://stackoverflow.com/questions/38381829/withrequired-no-extension-method-defined), [Equivalent for .HasOptional in Entity Framework Core](https://stackoverflow.com/questions/35562483/equivalent-for-hasoptional-in-entity-framework-core-1-ef7), which discuss how these methods can be adapter for EF Core.
