### ISSUE TITLE
RadDocking VisualStudio Implementation with MVVM sample

### ISSUE THREAD

**Issue by laurentkempe** [telerik/xaml-sdk#8]
This [sample](https://github.com/telerik/xaml-sdk/blob/master/Docking/VisualStudioDocking/ViewModel/MainWindowViewModel_WPF.cs#L70) cannot be considered as an MVVM sample. The ViewModel knows the View component which is against the MVVM principles.

**Comment by StefanX1** [comment]
Hello Laurent,

Please, excuse us for overlooking this issue. It seems indeed reasonable. Thus, I have logged an item in our backlog, so that the example is modified in a way that does not break the MVVM pattern.

All the best,
Stefan
